### ISSUE TITLE
Not seeing where lm_data/train.txt should come from

### ISSUE THREAD

**Issue by tybrad11** [CYBINT-IN/word-embeddings#9]
For the COVID-SciBERT notebook, what is: 

file_path = "lm_data/train.txt"

Where can I get this file? Is it just a partition of the clean_df.csv data?

**Comment by lordtt13** [comment]
They were created during initial data preprocessing/splitting [here](https://github.com/CYBINT-IN/word-embeddings/blob/master/COVID-19%20Research%20Data/COVID-ROBERTa.ipynb)
